theme: jekyll-theme-cayman
name: Hack&Health App
title: Hack&Health App
description: Winner solution of the Hack&Health 2016
repository: https://github.com/ebeneditos/Hack-Health-App
authors: Ernest Benedito, Gonzalo Espinosa & Sandra Orozco
show_downloads: true
